version: '2'
linters:
  default: all
  disable:
    - varnamelen # eventually
    - nlreturn # no need
    - exhaustruct_v5 # very noisy
    - gomodguard # deprecated
    - wsl # deprecated
    - exhaustruct # deprecated

  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - golift.io
            - gopkg.in/yaml.v3
    tagliatelle:
      case:
        rules:
          yaml: snake
  exclusions:
    rules:
      - path: .+_test.go
        linters:
          - goconst
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
